default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --flavor Production -t lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:302874334675:android:8e810e6025e75daa10cb26",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "fatimaatef990@gmail.com",
      release_notes: "First Fastlane App Distribution"
    )
  end
end
